version: '3'

tasks:
  default:
    desc: List Tasks.
    cmd: task -l

  run:coffee-break-simulator:
    desc: Run Coffee Break Simulator.
    dir: ./coffee-break-simulator
    cmd: quarkus dev

  run:native:coffee-break-simulator:
    desc: Run Coffee Break Simulator.
    dir: ./coffee-break-simulator
    cmd: target/coffee-break-simulator-runner

  build:native:coffee-break-simulator:
    desc: Build native image for Coffee Break Simulator.
    dir: ./coffee-break-simulator
    cmd: quarkus build --native --no-tests

  run:coffee-machine-service:
    desc: Run Coffee Machine Service.
    dir: ./coffee-machine-service
    cmd: quarkus dev

  run:native:coffee-machine-service:
    desc: Run Coffee Machine Service.
    dir: ./coffee-machine-service
    cmd: target/coffee-machine-service-runner

  build:coffee-machine-service:
    desc: Build Coffee Machine Service.
    dir: ./coffee-machine-service
    cmd: quarkus build

  build:native:coffee-machine-service:
    desc: Build native image for Coffee Machine Service.
    dir: ./coffee-machine-service
    cmd: quarkus build --native --no-tests

  build:native:lambda:coffee-machine-service:
    desc: Build native image for Coffee Machine Service - AWS Lambda.
    dir: ./coffee-machine-service
    cmd: quarkus build --native --no-tests -Dquarkus.native.container-build=true

  sam:local:invoke:native:coffee-machine-service:
    desc: Simulate Lambda invocation locally.
    dir: ./coffee-machine-service
    cmd: sam local invoke  -e event.json -t sam.native.yaml

  sam:local:invoke:jvm:coffee-machine-service:
    desc: Simulate Lambda invocation locally.
    dir: ./coffee-machine-service
    cmd: sam local invoke  -e event.json -t sam.jvm.yaml

  deploy:native:lambda:coffee-machine-service:
    desc: Deploy native image for Coffee Machine Service - AWS Lambda.
    dir: ./coffee-machine-service
    cmd: sam deploy -t sam.native.yaml --config-env native

  deploy:lambda:coffee-machine-service:
    desc: Deploy Coffee Machine Service - AWS Lambda.
    dir: ./coffee-machine-service
    cmd: sam deploy -t sam.jvm.yaml

  run:gossip-service:
    desc: Run Gossip Service.
    dir: ./gossip-service
    cmd: ./mvnw spring-boot:run

  run:native:gossip-service:
    desc: Run Gossip Service.
    dir: ./gossip-service
    cmd: target/gossip-service

  build:native:gossip-service:
    desc: Build native image for Gossip Service.
    dir: ./gossip-service
    cmd: ./mvnw clean -Pnative native:compile

  build:native:lambda:gossip-service:
    desc: Build native image for Gossip Service.
    dir: ./gossip-service
    cmds:
      - docker build -t al2023-graalvm21 -f Dockerfile.al2023-graalvm21 .
      - docker run -it -v `pwd`:/project  -v ~/.m2:/root/.m2 al2023-graalvm21 ./mvnw clean -Pnative package

  build:lambda:gossip-service:
    desc: Build native image for Gossip Service.
    dir: ./gossip-service
    cmd: ./mvnw clean -Plambda-java package

  sam:local:invoke:native:gossip-service:
    desc: Simulate Lambda invocation locally.
    dir: ./gossip-service
    cmd: sam local invoke  -e event.json -t sam.native.yaml

  sam:local:invoke:jvm:gossip-service:
    desc: Simulate Lambda invocation locally.
    dir: ./gossip-service
    cmd: sam local invoke  -e event.json -t sam.jvm.yaml

  deploy:native:lambda:gossip-service:
    desc: Deploy native image for Gossip Service - AWS Lambda.
    dir: ./gossip-service
    cmd: sam deploy -t sam.native.yaml --config-env native

  deploy:lambda:gossip-service:
    desc: Deploy Gossip Service - AWS Lambda.
    dir: ./gossip-service
    cmd: sam deploy -t sam.jvm.yaml

