version: '3'

tasks:
  default:
    desc: List Tasks.
    cmd: task -l

  run:coffee-break-simulator:
    desc: Run Coffee Break Simulator.
    dir: ./coffee-break-simulator
    cmd: quarkus dev

  run:native:coffee-break-simulator:
    desc: Run Coffee Break Simulator.
    dir: ./coffee-break-simulator
    cmd: target/coffee-break-simulator-runner

  build:native:coffee-break-simulator:
    desc: Build native image for Coffee Break Simulator.
    dir: ./coffee-break-simulator
    cmd: quarkus build --native --no-tests

  run:coffee-machine-service:
    desc: Run Coffee Machine Service.
    dir: ./coffee-machine-service
    cmd: quarkus dev

  run:native:coffee-machine-service:
    desc: Run Coffee Machine Service.
    dir: ./coffee-machine-service
    cmd: target/coffee-machine-service-runner

  build:coffee-machine-service:
    desc: Build Coffee Machine Service.
    dir: ./coffee-machine-service
    cmd: quarkus build

  build:native:coffee-machine-service:
    desc: Build native image for Coffee Machine Service.
    dir: ./coffee-machine-service
    cmd: quarkus build --native --no-tests

  build:native:lambda:coffee-machine-service:
    desc: Build native image for Coffee Machine Service - AWS Lambda.
    dir: ./coffee-machine-service
    cmds:
      - ./mvnw clean
      - quarkus build --native --no-tests -Dquarkus.native.container-build=true -Dmusic.skip=false

  deploy:native:lambda:coffee-machine-service:
    desc: Deploy native image for Coffee Machine Service - AWS Lambda.
    dir: ./coffee-machine-service/lambda
    cmds:
      - mkdir -p .sam-deploy-native
      - cp ../target/coffee-machine-service-runner .sam-deploy-native
      - cp bootstrap .sam-deploy-native
      - sam deploy -t sam.native.yaml --config-env native

  deploy:lambda:coffee-machine-service:
    desc: Deploy Coffee Machine Service - AWS Lambda.
    dir: ./coffee-machine-service/lambda
    cmds:
      - mkdir -p .sam-deploy-java
      - cp -R ../target/quarkus-app/* .sam-deploy-java
      - cp run.sh .sam-deploy-java
      - sam deploy -t sam.jvm.yaml

  run:gossip-service:
    desc: Run Gossip Service.
    dir: ./gossip-service
    cmd: ./mvnw spring-boot:run

  run:native:gossip-service:
    desc: Run Gossip Service.
    dir: ./gossip-service
    cmd: target/gossip-service

  build:native:gossip-service:
    desc: Build native image for Gossip Service.
    dir: ./gossip-service
    cmd: ./mvnw clean -Pnative native:compile

  build:gossip-service:
    desc: Build Gossip Service.
    dir: ./gossip-service
    cmd: ./mvnw clean package

  build:native:lambda:gossip-service:
    desc: Build native image for Gossip Service.
    dir: ./gossip-service
    cmds:
      - docker build -t al2023-graalvm25 -f Dockerfile.al2023-graalvm25 .
      - docker run -it -v `pwd`:/project  -v ~/.m2:/root/.m2 al2023-graalvm25 ./mvnw clean -Pnative -Dmusic.skip=false native:compile

  deploy:native:lambda:gossip-service:
    desc: Deploy native image for Gossip Service - AWS Lambda.
    dir: ./gossip-service/lambda
    cmds:
      - mkdir -p .sam-deploy-native
      - cp ../target/gossip-service .sam-deploy-native
      - cp bootstrap .sam-deploy-native
      - sam deploy -t sam.native.yaml --config-env native

  deploy:lambda:gossip-service:
    desc: Deploy Gossip Service - AWS Lambda.
    dir: ./gossip-service/lambda
    cmds:
      - mkdir -p .sam-deploy-java
      - cp ../target/gossip-service.jar .sam-deploy-java/app.jar
      - cp run.sh .sam-deploy-java
      - sam deploy -t sam.jvm.yaml